### ISSUE TITLE
Este Projeto ainda está em Andamento?

### ISSUE THREAD

**Issue by SpectroKandoro** [AnarcoTraducoes/eastward-ptbr#1]
Eu descobri Eastward muito recentemente e me apaixonei completamente pelo jogo, admirando muito a iniciativa de traduzi-lo visto que este pode ser um modo muito efetivo de popularizá-lo aqui no Brasil. Enfim, quero contribuir, mas gostaria de saber se o projeto segue em andamento...

**Comment by srtiagomarques** [comment]
Olá Spectro, sim o projeto ainda está em andamento. No momento ele encontra-se totalmente traduzido (exceto textos que são imagens, ex: As apresentações dos capítulos e placas dentro do game), ai estamos dando continuidade nas revisões das traduções. Acabamos de finalizar a revisão do primeiro capítulo, mas não quer dizer que possivelmente não necessite de mais coisas. Ficaríamos muito felizes se você pudece nos auxiliar, da formar que melhor lhe convir :)

**Comment by SpectroKandoro** [comment]
Bem, creio que posso ajudar na revisão dos capítulos conseguintes então?

**Comment by srtiagomarques** [comment]
Pode sim, fico no aguardo dos seus Pull Requests :)
