### ISSUE TITLE
Legenda da DLC.

### ISSUE THREAD

**Issue by OneEyeBlack** [AnarcoTraducoes/eastward-ptbr#2]
Olá e obrigado pelo seu trabalho.

Eu estou um pouco confuso com a explicação que você deixara sobre onde colocar a legenda quando se tem a DLC instalada.

A estrutura que tenho é essa:
This PC\Switch\1: SD Card\atmosphere\contents\010071B00F63A000\romfs\game\locale.g <- arquivo de tradução
ou essa
This PC\Switch\4: Installed games\Eastward\010071B00F63A000\romfs\game\locale.g <- arquivo de tradução

Seguindo o caminho acima, onde coloco o arquivo de tradução quando se tem a DLC instalada?
Precisa criar uma pasta nova?

Agradeço a ajuda.

**Comment by OneEyeBlack** [comment]
Consegui. Obrigado.  ;)

**Comment by thiarthur** [comment]
Fico feliz que conseguiu! 
Para quem possuir a dlc e tiver esta dúvida, é preciso copiar o locale.g para ```...\Eastward\content\game\``` e também ```...\Eastward\content_dlc\```
