### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by sexowrld** [AnarcoTraducoes/eastward-ptbr#5]
a maioria dos npc em new daw city estão sem fala nenhuma so fica me branco quando a gnt vai interagir, ajudem!

**Comment by srtiagomarques** [comment]
Olá, estou trabalhando nessa correção, postarei um novo release o mais rápido possível. Muito obrigado pelo feedback.

**Comment by srtiagomarques** [comment]
Correção postada, release v0.0.11
